# Generated by Django 4.2.20 on 2025-03-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
